// ====================================================================
// Data — Aakar Kale's portfolio content
// ====================================================================

export const AK_DATA = {
  name: 'Aakar Kale',
  role: 'Senior Product Manager',
  tagline: 'Ex-founder turned Senior PM, turning ambiguity into outcomes. Shaping the next generation of products with clarity and purpose.',
  location: 'San Francisco, CA',
  origin: 'Mumbai, India',

  stats: [
    { num: '10+', label: 'Years in tech', tooltip: 'From Founder to Project Manager to Consultant to Product Manager', tooltipBend: 'L' },
    { num: '6',  label: 'Years in product' },
    { num: '3M+', label: 'Users served', animate: { from: 100000, to: 3000000, fmt: 'magnitude' } },
    { num: '5', label: 'Industries', tooltip: 'Shipped across 5 Industries — Auto-Retail, Healthcare, Telecom, Venture Capital, Consumer Retail', tooltipBend: 'reverseL' },
  ],

  about: [
    "I've always introduced myself as an engineer and a tech enthusiast — someone who tears apart how things work and gets a kick out of putting them back together, better. MKBHD and the smartphone revolution pulled me into tech. These days it's the architecture behind large language models and the craft of building products that millions of people actually use.",
    "Born and raised in Mumbai, currently living in San Francisco — chasing childhood dreams in Silicon Valley. You'll find me frequenting city beaches, looking for answers to life's questions and a good spot to catch the sunset.",
    "I'm a PM who thinks in data. Machine learning and data science aren't buzzwords on my resume — they're how I think about problems: find the signal, test the hypothesis, ship the thing, measure what happens.",
    "I'm a product manager, a data engineer, a startup enthusiast, a videographer, a marathon runner, a proud son, a loving brother, and a lifetime student. I'm an optimist who believes consistent hard work almost always beats smart work.",
  ],

  experience: [
    {
      role: 'Senior Product Manager, Growth',
      company: 'DGDG, Inc.',
      place: 'San Jose, CA',
      period: 'May 2023 — Present',
      bullets: [
        'Shipped an LLM voice agent + call-intelligence feature on Dialpad in 3 months; 50+ dealership call centers auto-route Salesforce actions with zero human review.',
        'Owned AcquireCars (patent filed) end-to-end — an AI/ML acquisition platform on AWS — lifting free-to-paid conversion +11% and cutting time-to-value 58% (12 → 5 days).',
        'Closed customer feedback loops with 50–60 dealerships; live call transcripts fed straight into sprint priorities and agent refinement.',
        'Ran A/B experiments across onboarding + activation with eng/design/data; +30% operational efficiency, with quarterly AI/ML strategy briefings to C-suite.',
      ],
    },
    {
      role: 'Technology Consultant — Product Org',
      company: 'ZS Associates',
      place: 'San Francisco, CA',
      period: 'Feb 2021 — May 2023',
      bullets: [
        'Owned strategy for a healthcare IoT B2B SaaS — 6 releases/quarter across 16 pilots, CSAT +30%, 99.95% uptime at ~450ms ingest.',
        'Ran 180+ usability sessions with 60+ clinicians on an AI clinical decision tool: acceptance +17%, diagnostic turnaround −14%, onboarding −43%.',
        'Led a B2B telemedicine platform (PRDs, wireframes, API specs): appointment completion +12%, feature adoption +62%, NPS +11 post-launch.',
        'Briefed senior leadership and client execs on ML model performance and product strategy across parallel B2B engagements.',
      ],
    },
    {
      role: 'Data Engineering Intern',
      company: 'T-Mobile USA',
      place: 'Bellevue, WA',
      period: 'Jun 2019 — Aug 2019',
      bullets: [
        'Built a real-time 5G rollout dashboard (Python/SQL/Azure/Power BI) adopted by 200+ reps across 12 regions; coverage answers 10 min → 30 sec (−95%), 99.9% uptime.',
        'Forecast peak demand with Python time-series (~7% MAPE); hotspot fixes cut outages −19% and call-drops −14%.',
      ],
    },
    {
      role: 'Project Manager, M&A Lead',
      company: 'Navayuvak Entrepreneurs',
      place: 'Mumbai, India',
      period: 'Jun 2017 — Jul 2018',
      bullets: [
        'Built C-suite relationships with 80+ CEOs, VCs, and enterprise buyers; QBRs tying roadmap to ROI unlocked $1.45M in funding, pilots, and co-sell deals.',
        'Built an executive feedback engine wiring signals into roadmap prioritization; NPS +12 across 75+ portfolio companies.',
        'Systematized discovery across 500+ founders into PRDs and GTM plays for 5 fintech offerings; time-to-launch −35%, accelerator 6× YoY revenue.',
      ],
    },
    {
      role: 'Co-Founder & CEO',
      company: 'Bookmarked Inc.',
      place: 'Mumbai, India',
      period: 'Oct 2014 — Jan 2017',
      bullets: [
        'Scaled a B2C book marketplace 0→1 with a 24-person team built from scratch; break-even in 3 months, INR 900k revenue by Q4.',
        'Sold 50k+ books to 15k+ customers, owning the full product, ops, and growth stack.',
        'Ran GA, CrazyEgg, and Marketo to iterate UX and accelerate acquisition via data-driven content + conversion gains.',
      ],
    },
  ],

  projects: [
    {
      id: 'archly',
      index: '01',
      title: 'Archly AI',
      oneLiner: 'LLM-powered voice interview coach with RAG and agentic capabilities.',
      tags: ['RAG', 'LLM', 'Voice AI', 'Cursor'],
      accent: 'rgb(115,115,255)',
      url: 'https://archly.dev/',
    },
    {
      id: 'alignmoney',
      index: '02',
      title: 'AlignMoney',
      oneLiner: 'AI-powered personal finance with smart budgeting and intelligent investing.',
      tags: ['FinTech', 'AI', 'Replit'],
      accent: 'rgb(4,196,10)',
      url: 'https://align-money-aakarsidehustle.replit.app/',
    },
    {
      id: 'biotracker',
      index: '03',
      title: 'BioTracker',
      oneLiner: 'ML-powered health analytics hub for biomarker tracking and personalized insights.',
      tags: ['Machine Learning', 'HealthTech', 'Analytics'],
      accent: 'rgb(255,133,115)',
      url: 'https://bio-tracker-rouge.vercel.app/',
    },
    {
      id: 'photocloud',
      index: '04',
      title: 'PhotoCloudCRM',
      oneLiner: 'AI-integrated photo business platform with built-in CRM workflows.',
      tags: ['CRM', 'SaaS'],
      accent: 'rgb(255,221,85)',
      url: 'https://photo-cloud-studio.replit.app/',
    },
    {
      id: 'aurafocus',
      index: '05',
      title: 'Aura Focus AR',
      oneLiner: 'AR smart glasses that pin voice reminders to real-world spots around your home — built for ADHD focus.',
      tags: ['AR', 'Voice AI', 'ADHD'],
      accent: 'rgb(41,149,255)',
      url: 'https://aura-focus.replit.app',
    },
    {
      id: 'traffic',
      index: '06',
      title: 'Traffic Camera Alert',
      oneLiner: 'Born from one expensive lesson at a notorious SF intersection.',
      tags: ['Real-time', 'Alerts'],
      accent: 'rgb(255,69,56)',
      url: 'https://traffic-camera-alert.replit.app/',
    },
    {
      id: 'potluck',
      index: '07',
      title: 'Potluck',
      oneLiner: 'Share one link so everyone sees what’s on the table — no more six identical pasta salads.',
      tags: ['Events', 'Social', 'Web App'],
      accent: 'rgb(255,107,53)',
      url: 'https://potluck.aakarkale.com/',
    },
  ],

  secretProject: {
    id: 'secret',
    index: '??',
    title: 'The Konami Project',
    oneLiner: "You found the cheat code. A scrappy prototype I'm still tinkering with on weekends.",
    tags: ['Secret', 'WIP', 'Easter Egg'],
    accent: 'rgb(255,0,128)',
  },

  skills: [
    { group: 'AI/ML & LLM', items: ['RAG', 'Agentic Workflows', 'Prompt Engineering', 'TensorFlow', 'Keras', 'Scikit-Learn', 'PySpark'] },
    { group: 'AI Coding', items: ['Cursor', 'Claude Code', 'Replit Agent', 'Lovable', 'Gemini Code Assist'] },
    { group: 'Languages', items: ['Python', 'JavaScript', 'TypeScript', 'SQL', 'Java', 'R'] },
    { group: 'Cloud', items: ['AWS (EC2, S3, Lambda, Redshift)', 'GCP', 'Azure'] },
    { group: 'Data', items: ['Tableau', 'Power BI', 'Pandas', 'NumPy', 'Dovetail AI'] },
    { group: 'Product & Design', items: ['Figma', 'Jira', 'Confluence', 'Productboard', 'Airtable'] },
  ],

  // Each item: {name, slug?}. `slug` is a Simple Icons slug (cdn.simpleicons.org/{slug}).
  // If slug is missing OR the request 404s, the UI falls back to the name as text.
  techReel: [
    { name: 'Figma', slug: 'figma' },
    { name: 'Jira', slug: 'jira' },
    { name: 'Confluence', slug: 'confluence' },
    { name: 'Productboard' },
    { name: 'Aha!' },
    { name: 'Airtable', slug: 'airtable' },
    { name: 'Notion', slug: 'notion' },
    { name: 'Linear', slug: 'linear' },
    { name: 'Miro', slug: 'miro' },
    { name: 'FigJam' },
    { name: 'Loom', slug: 'loom' },
    { name: 'Mixpanel', slug: 'mixpanel' },
    { name: 'Segment', slug: 'segment' },
    { name: 'Pendo' },
    { name: 'Heap' },
    { name: 'LaunchDarkly', slug: 'launchdarkly' },
    { name: 'Tableau', slug: 'tableau' },
    { name: 'Power BI', slug: 'powerbi' },
    { name: 'Looker', slug: 'looker' },
    { name: 'Google Analytics', slug: 'googleanalytics' },
    { name: 'Dovetail', slug: 'dovetail' },
    { name: 'UserTesting' },
    { name: 'Cursor', slug: 'cursor' },
    { name: 'Claude Code', slug: 'anthropic' },
    { name: 'Replit', slug: 'replit' },
    { name: 'Lovable' },
    { name: 'Gemini Code Assist', slug: 'googlegemini' },
    { name: 'Hugging Face', slug: 'huggingface' },
    { name: 'TensorFlow', slug: 'tensorflow' },
    { name: 'AWS', slug: 'amazonwebservices' },
    { name: 'GCP', slug: 'googlecloud' },
    { name: 'Azure', slug: 'microsoftazure' },
    { name: 'BigQuery', slug: 'googlebigquery' },
    { name: 'Redshift', slug: 'amazonredshift' },
    { name: 'Snowflake', slug: 'snowflake' },
    { name: 'GitHub', slug: 'github' },
    { name: 'Vercel', slug: 'vercel' },
    { name: 'Postman', slug: 'postman' },
    { name: 'Datadog', slug: 'datadog' },
    { name: 'TypeScript', slug: 'typescript' },
    { name: 'Salesforce', slug: 'salesforce' },
    { name: 'HubSpot', slug: 'hubspot' },
    { name: 'Marketo', slug: 'marketo' },
    { name: 'Stripe', slug: 'stripe' },
    { name: 'Zendesk', slug: 'zendesk' },
  ],

  education: [
    { degree: 'M.S. in Business Analytics & Data Science', school: 'Cal State East Bay', period: '2019 — 2020', url: 'https://www.csueastbay.edu/', logo: { file: 'assets/logos/csueastbay.png', domain: 'csueastbay.edu', mono: 'EB', accent: '#BA0C2F' } },
    { degree: 'M.S. in Information Systems Management', school: 'Santa Clara University', period: '2018 — 2019', url: 'https://www.scu.edu/', logo: { file: 'assets/logos/scu.png', domain: 'scu.edu', mono: 'SCU', accent: '#862633' } },
    { degree: 'B.E. in Information Technology', school: 'Mumbai University', period: '2012 — 2017', url: 'https://mu.ac.in/', logo: { file: 'assets/logos/mumbai.png', domain: 'mu.ac.in', mono: 'MU', accent: '#1B3A6B' } },
  ],

  certifications: [
    { name: 'Salesforce Certified Advanced Administrator', year: '2025', note: 'Held by 15% of certified professionals', url: 'https://trailhead.salesforce.com/en/credentials/verification/', logo: { file: 'assets/logos/salesforce.png', domain: 'salesforce.com', mono: 'SF', accent: '#00A1E0' } },
    { name: 'FAA-Certified Drone Pilot (Part 107)', year: '2021', note: 'See my YouTube Channel', url: 'https://youtube.com/@aakarkale', logo: { domain: 'faa.gov', mono: 'FAA', accent: '#1A4D8F' } },
  ],

  papers: [
    { title: 'Number Plate Recognition System: A Smart City Solution', pub: 'IRJET · Vol 4, Issue 12', year: 'Dec 2017', url: './papers/Number.Plate.Recognition.System.pdf' },
    { title: '3D Face Recognition Technology in Network Security Applications', pub: 'IRJET · Vol 4, Issue 12', year: 'Dec 2017', url: './papers/3D.Face.Recognition.Technology.pdf' },
  ],

  contact: {
    email: 'aakararunkale@gmail.com',
    linkedin: 'https://linkedin.com/in/aakarkale',
    x: 'https://x.com/aakarkale',
    youtube: 'https://www.youtube.com/channel/UCi_Gt1HFpBS5p3TSLlkP6Kw',
  },
};
